name: "Blog of Hajar6"
description: "Knowledge collection"

url: "https://hajar6.github.io/blog"
loadingImg: "https://hajar6.github.io/blog/img/loading.gif"
filePath: "https://hajar6.github.io/blog/img/"

timezone: Asia/Shenzhen

paginate: 16
paginate_path: "/page:num"

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

permalink: pretty

gems:
- jekyll-paginate
